// @ts-check
export const STATE=Object.freeze({IDLE:'IDLE',FILLING_SLOTS:'FILLING_SLOTS',RESOLVING:'RESOLVING',PRESENTING:'PRESENTING',FEEDBACK:'FEEDBACK'});
/** @type {Record<string,string[]>} */
export const TRANSITIONS=Object.freeze({IDLE:['FILLING_SLOTS','RESOLVING'],FILLING_SLOTS:['RESOLVING','IDLE'],RESOLVING:['PRESENTING','FILLING_SLOTS'],PRESENTING:['FEEDBACK','IDLE'],FEEDBACK:['IDLE']});
